# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
  - "public/js/dist/*"
  - "tests/_support/_generated/AcceptanceTesterActions.php"
  - "tests/acceptance/AcceptanceTester.php"