language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - phpenv config-add phpconfig.ini
  - composer self-update
  - composer install
script:
  - ./phpunit.sh
notfications:
  email:
    on_success: always
    on_failure: always
